version: '3.8'

services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        image: joanmi_laravel8
        container_name: www
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: www
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8001:80"
        networks:
            - www-network

    db:
        image: mysql:5.7
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - www-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - www-network

volumes:
    db_data:

networks:
    www-network:
        driver: bridge
